namespace BehaviorDesigner.Editor
{
    public enum BDPreferences
    {
        ShowWelcomeScreen,
        ShowSceneIcon,
        ShowHierarchyIcon,
        OpenInspectorOnTaskSelection,
        OpenInspectorOnTaskDoubleClick,
        FadeNodes,
        EditablePrefabInstances,
        PropertiesPanelOnLeft,
        MouseWhellScrolls,
        FoldoutFields,
        CompactMode,
        SnapToGrid,
        ShowTaskDescription,
        BinarySerialization,
        UndoRedo,
        ErrorChecking,
        SelectOnBreakpoint,
        UpdateCheck,
        AddGameGUIComponent,
        GizmosViewMode,
        QuickSearchKeyCode,
        ZoomSpeedMultiplier,
        Last
    }
}